POST http://localhost:3003/api/blogs/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImxpaXNhbWFqIiwiaWQiOiI2Njc5YWM4YTgxM2I1YTZlMzE2Y2ZkNTUiLCJpYXQiOjE3MTkzMzU0NDB9.kKdeikIEUBv62Ive2i7VG-YVo4lUCYFsM-vvP4cBzTY

{
    "title": "Full Stack Open 2024 course's learning blog",
    "author": "Liisa Majuri",
    "url": "https://gitlab.dclabra.fi/wiki/ExPwnLaxSeeNa7SLuVa6MQ?",
    "likes": 1
}
